package grain.entity;

import javax.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

@Getter
@Setter
@ToString
@Accessors(chain = true)
@Table(name = "ringtone_video_videotask")
public class RingtoneVideoVideotask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.id
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.name
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.brief_picture
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String briefPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.user_id
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.state
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.category_id
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.token
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.video_relative_path
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String videoRelativePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.video_create_info
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String videoCreateInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.time_length
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer timeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.create_time
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.created_time
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private String createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.ref_task_id
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer refTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask.frequency_use
     *
     * @mbg.generated Thu Nov 28 12:16:55 CST 2019
     */
    private Integer frequencyUse;
}