package grain.entity;

import javax.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

@Getter
@Setter
@ToString
@Accessors(chain = true)
@Table(name = "ringtone_video_videotask_category")
public class RingtoneVideoVideotaskCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask_category.id
     *
     * @mbg.generated Thu Nov 28 12:17:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask_category.task_id
     *
     * @mbg.generated Thu Nov 28 12:17:02 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask_category.category_id
     *
     * @mbg.generated Thu Nov 28 12:17:02 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask_category.dimension
     *
     * @mbg.generated Thu Nov 28 12:17:02 CST 2019
     */
    private String dimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_videotask_category.create_time
     *
     * @mbg.generated Thu Nov 28 12:17:02 CST 2019
     */
    private String createTime;
}