package grain.entity;

import javax.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

@Getter
@Setter
@ToString
@Accessors(chain = true)
@Table(name = "ringtone_video_font")
public class RingtoneVideoFont {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.id
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.user_id
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.category_id
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.name
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.name_cn
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private String nameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.relative_path
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private String relativePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_font.create_time
     *
     * @mbg.generated Thu Nov 28 12:16:28 CST 2019
     */
    private String createTime;
}