package grain.entity;

import javax.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

@Getter
@Setter
@ToString
@Accessors(chain = true)
@Table(name = "ringtone_video_material")
public class RingtoneVideoMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.id
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.name
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.user_id
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.user_phone_number
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String userPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.category_id
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.type
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.relative_path
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String relativePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.picture_path
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String picturePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.time_length
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private Integer timeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.expire_date
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ringtone_video_material.create_date
     *
     * @mbg.generated Thu Nov 28 12:16:36 CST 2019
     */
    private String createDate;
}