package org.grain;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

public final class Service {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_CheckReq_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_CheckReq_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_CheckReq_MapEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_CheckReq_MapEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Resp_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Resp_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rservice.proto\"W\n\010CheckReq\022\037\n\003map\030\001 \003(\013" +
                        "2\022.CheckReq.MapEntry\032*\n\010MapEntry\022\013\n\003key\030" +
                        "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"/\n\004Resp\022\031\n\004code" +
                        "\030\001 \002(\0162\013.StatusCode\022\014\n\004desc\030\002 \002(\t*#\n\nSta" +
                        "tusCode\022\013\n\007SUCCESS\020\001\022\010\n\004FAIL\020\0022\'\n\005Hello\022" +
                        "\036\n\010sayHello\022\t.CheckReq\032\005.Resp\"\000"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_CheckReq_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_CheckReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_CheckReq_descriptor,
                new java.lang.String[]{"Map",});
        internal_static_CheckReq_MapEntry_descriptor =
                internal_static_CheckReq_descriptor.getNestedTypes().get(0);
        internal_static_CheckReq_MapEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_CheckReq_MapEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_Resp_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Resp_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Resp_descriptor,
                new java.lang.String[]{"Code", "Desc",});
    }

    private Service() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    /**
     * Protobuf enum {@code StatusCode}
     */
    public enum StatusCode
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SUCCESS = 1;</code>
         */
        SUCCESS(1),
        /**
         * <code>FAIL = 2;</code>
         */
        FAIL(2),
        ;

        /**
         * <code>SUCCESS = 1;</code>
         */
        public static final int SUCCESS_VALUE = 1;
        /**
         * <code>FAIL = 2;</code>
         */
        public static final int FAIL_VALUE = 2;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                StatusCode> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
                    public StatusCode findValueByNumber(int number) {
                        return StatusCode.forNumber(number);
                    }
                };
        private static final StatusCode[] VALUES = values();
        private final int value;

        private StatusCode(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static StatusCode valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static StatusCode forNumber(int value) {
            switch (value) {
                case 1:
                    return SUCCESS;
                case 2:
                    return FAIL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return Service.getDescriptor().getEnumTypes().get(0);
        }

        public static StatusCode valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:StatusCode)
    }

    public interface CheckReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:CheckReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        int getMapCount();

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        boolean containsMap(
                java.lang.String key);

        /**
         * Use {@link #getMapMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getMap();

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getMapMap();

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        /* nullable */
        java.lang.String getMapOrDefault(
                java.lang.String key,
                /* nullable */
                java.lang.String defaultValue);

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        java.lang.String getMapOrThrow(
                java.lang.String key);
    }

    public interface RespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Resp)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return Whether the code field is set.
         */
        boolean hasCode();

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return The code.
         */
        Service.StatusCode getCode();

        /**
         * <code>required string desc = 2;</code>
         *
         * @return Whether the desc field is set.
         */
        boolean hasDesc();

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The desc.
         */
        java.lang.String getDesc();

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The bytes for desc.
         */
        com.google.protobuf.ByteString
        getDescBytes();
    }

    /**
     * Protobuf type {@code CheckReq}
     */
    public static final class CheckReq extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:CheckReq)
            CheckReqOrBuilder {
        public static final int MAP_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:CheckReq)
        private static final Service.CheckReq DEFAULT_INSTANCE;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<CheckReq>
                PARSER = new com.google.protobuf.AbstractParser<CheckReq>() {
            @java.lang.Override
            public CheckReq parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new Service.CheckReq();
        }

        @SuppressWarnings("serial")
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> map_;
        private byte memoizedIsInitialized = -1;

        // Use CheckReq.newBuilder() to construct.
        private CheckReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private CheckReq() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Service.internal_static_CheckReq_descriptor;
        }

        public static Service.CheckReq parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Service.CheckReq parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Service.CheckReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Service.CheckReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Service.CheckReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Service.CheckReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Service.CheckReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Service.CheckReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Service.CheckReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Service.CheckReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Service.CheckReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Service.CheckReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Service.CheckReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Service.CheckReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<CheckReq> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new CheckReq();
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetMap();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Service.internal_static_CheckReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Service.CheckReq.class, Service.CheckReq.Builder.class);
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMap() {
            if (map_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MapDefaultEntryHolder.defaultEntry);
            }
            return map_;
        }

        public int getMapCount() {
            return internalGetMap().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @java.lang.Override
        public boolean containsMap(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetMap().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMapMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getMap() {
            return getMapMap();
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @java.lang.Override
        public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
            return internalGetMap().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @java.lang.Override
        public /* nullable */
        java.lang.String getMapOrDefault(
                java.lang.String key,
                /* nullable */
                java.lang.String defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMap().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @java.lang.Override
        public java.lang.String getMapOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMap().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetMap(),
                            MapDefaultEntryHolder.defaultEntry,
                            1);
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetMap().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, map__);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Service.CheckReq)) {
                return super.equals(obj);
            }
            Service.CheckReq other = (Service.CheckReq) obj;

            if (!internalGetMap().equals(
                    other.internalGetMap())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetMap().getMap().isEmpty()) {
                hash = (37 * hash) + MAP_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMap().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<CheckReq> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Service.CheckReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class MapDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    Service.internal_static_CheckReq_MapEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        /**
         * Protobuf type {@code CheckReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:CheckReq)
                Service.CheckReqOrBuilder {
            private int bitField0_;
            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> map_;

            // Construct using Service.CheckReq.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Service.internal_static_CheckReq_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMap();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableMap();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Service.internal_static_CheckReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Service.CheckReq.class, Service.CheckReq.Builder.class);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                internalGetMutableMap().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Service.internal_static_CheckReq_descriptor;
            }

            @java.lang.Override
            public Service.CheckReq getDefaultInstanceForType() {
                return Service.CheckReq.getDefaultInstance();
            }

            @java.lang.Override
            public Service.CheckReq build() {
                Service.CheckReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Service.CheckReq buildPartial() {
                Service.CheckReq result = new Service.CheckReq(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(Service.CheckReq result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.map_ = internalGetMap();
                    result.map_.makeImmutable();
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Service.CheckReq) {
                    return mergeFrom((Service.CheckReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Service.CheckReq other) {
                if (other == Service.CheckReq.getDefaultInstance()) return this;
                internalGetMutableMap().mergeFrom(
                        other.internalGetMap());
                bitField0_ |= 0x00000001;
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                        map__ = input.readMessage(
                                        MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                                internalGetMutableMap().getMutableMap().put(
                                        map__.getKey(), map__.getValue());
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMap() {
                if (map_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MapDefaultEntryHolder.defaultEntry);
                }
                return map_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableMap() {
                if (map_ == null) {
                    map_ = com.google.protobuf.MapField.newMapField(
                            MapDefaultEntryHolder.defaultEntry);
                }
                if (!map_.isMutable()) {
                    map_ = map_.copy();
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return map_;
            }

            public int getMapCount() {
                return internalGetMap().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @java.lang.Override
            public boolean containsMap(
                    java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                return internalGetMap().getMap().containsKey(key);
            }

            /**
             * Use {@link #getMapMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getMap() {
                return getMapMap();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @java.lang.Override
            public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
                return internalGetMap().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @java.lang.Override
            public /* nullable */
            java.lang.String getMapOrDefault(
                    java.lang.String key,
                    /* nullable */
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetMap().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @java.lang.Override
            public java.lang.String getMapOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetMap().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMap() {
                bitField0_ = (bitField0_ & ~0x00000001);
                internalGetMutableMap().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            public Builder removeMap(
                    java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                internalGetMutableMap().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableMap() {
                bitField0_ |= 0x00000001;
                return internalGetMutableMap().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            public Builder putMap(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                if (value == null) {
                    throw new NullPointerException("map value");
                }
                internalGetMutableMap().getMutableMap()
                        .put(key, value);
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            public Builder putAllMap(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableMap().getMutableMap()
                        .putAll(values);
                bitField0_ |= 0x00000001;
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:CheckReq)
        }

    }

    /**
     * Protobuf type {@code Resp}
     */
    public static final class Resp extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Resp)
            RespOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int DESC_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Resp)
        private static final Service.Resp DEFAULT_INSTANCE;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Resp>
                PARSER = new com.google.protobuf.AbstractParser<Resp>() {
            @java.lang.Override
            public Resp parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new Service.Resp();
        }

        private int bitField0_;
        private int code_ = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object desc_ = "";
        private byte memoizedIsInitialized = -1;

        // Use Resp.newBuilder() to construct.
        private Resp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Resp() {
            code_ = 1;
            desc_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Service.internal_static_Resp_descriptor;
        }

        public static Service.Resp parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Service.Resp parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Service.Resp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Service.Resp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Service.Resp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Service.Resp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Service.Resp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Service.Resp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Service.Resp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Service.Resp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Service.Resp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Service.Resp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Service.Resp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Service.Resp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Resp> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Resp();
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Service.internal_static_Resp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Service.Resp.class, Service.Resp.Builder.class);
        }

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return Whether the code field is set.
         */
        @java.lang.Override
        public boolean hasCode() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return The code.
         */
        @java.lang.Override
        public Service.StatusCode getCode() {
            Service.StatusCode result = Service.StatusCode.forNumber(code_);
            return result == null ? Service.StatusCode.SUCCESS : result;
        }

        /**
         * <code>required string desc = 2;</code>
         *
         * @return Whether the desc field is set.
         */
        @java.lang.Override
        public boolean hasDesc() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The desc.
         */
        @java.lang.Override
        public java.lang.String getDesc() {
            java.lang.Object ref = desc_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    desc_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The bytes for desc.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getDescBytes() {
            java.lang.Object ref = desc_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDesc()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeEnum(1, code_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, code_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Service.Resp)) {
                return super.equals(obj);
            }
            Service.Resp other = (Service.Resp) obj;

            if (hasCode() != other.hasCode()) return false;
            if (hasCode()) {
                if (code_ != other.code_) return false;
            }
            if (hasDesc() != other.hasDesc()) return false;
            if (hasDesc()) {
                if (!getDesc()
                        .equals(other.getDesc())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasCode()) {
                hash = (37 * hash) + CODE_FIELD_NUMBER;
                hash = (53 * hash) + code_;
            }
            if (hasDesc()) {
                hash = (37 * hash) + DESC_FIELD_NUMBER;
                hash = (53 * hash) + getDesc().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Resp> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Service.Resp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Resp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Resp)
                Service.RespOrBuilder {
            private int bitField0_;
            private int code_ = 1;
            private java.lang.Object desc_ = "";

            // Construct using Service.Resp.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Service.internal_static_Resp_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Service.internal_static_Resp_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Service.Resp.class, Service.Resp.Builder.class);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = 1;
                desc_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Service.internal_static_Resp_descriptor;
            }

            @java.lang.Override
            public Service.Resp getDefaultInstanceForType() {
                return Service.Resp.getDefaultInstance();
            }

            @java.lang.Override
            public Service.Resp build() {
                Service.Resp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Service.Resp buildPartial() {
                Service.Resp result = new Service.Resp(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(Service.Resp result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.desc_ = desc_;
                    to_bitField0_ |= 0x00000002;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Service.Resp) {
                    return mergeFrom((Service.Resp) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Service.Resp other) {
                if (other == Service.Resp.getDefaultInstance()) return this;
                if (other.hasCode()) {
                    setCode(other.getCode());
                }
                if (other.hasDesc()) {
                    desc_ = other.desc_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasCode()) {
                    return false;
                }
                if (!hasDesc()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                int tmpRaw = input.readEnum();
                                Service.StatusCode tmpValue =
                                        Service.StatusCode.forNumber(tmpRaw);
                                if (tmpValue == null) {
                                    mergeUnknownVarintField(1, tmpRaw);
                                } else {
                                    code_ = tmpRaw;
                                    bitField0_ |= 0x00000001;
                                }
                                break;
                            } // case 8
                            case 18: {
                                desc_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @return Whether the code field is set.
             */
            @java.lang.Override
            public boolean hasCode() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @return The code.
             */
            @java.lang.Override
            public Service.StatusCode getCode() {
                Service.StatusCode result = Service.StatusCode.forNumber(code_);
                return result == null ? Service.StatusCode.SUCCESS : result;
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(Service.StatusCode value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                code_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 1;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return Whether the desc field is set.
             */
            public boolean hasDesc() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return The desc.
             */
            public java.lang.String getDesc() {
                java.lang.Object ref = desc_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        desc_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @param value The desc to set.
             * @return This builder for chaining.
             */
            public Builder setDesc(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                desc_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return The bytes for desc.
             */
            public com.google.protobuf.ByteString
            getDescBytes() {
                java.lang.Object ref = desc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    desc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @param value The bytes for desc to set.
             * @return This builder for chaining.
             */
            public Builder setDescBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                desc_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDesc() {
                desc_ = getDefaultInstance().getDesc();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Resp)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
