package org.grain;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

public final class Service {
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_CheckReq_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_CheckReq_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_CheckReq_MapEntry_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_CheckReq_MapEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Resp_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Resp_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\rservice.proto\"W\n\010CheckReq\022\037\n\003map\030\001 \003(\013" + "2\022.CheckReq.MapEntry\032*\n\010MapEntry\022\013\n\003key\030" + "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"/\n\004Resp\022\031\n\004code" + "\030\001 \002(\0162\013.StatusCode\022\014\n\004desc\030\002 \002(\t*#\n\nSta" + "tusCode\022\013\n\007SUCCESS\020\001\022\010\n\004FAIL\020\0022\'\n\005Hello\022" + "\036\n\010sayHello\022\t.CheckReq\032\005.Resp\"\000"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{});
        internal_static_CheckReq_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_CheckReq_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_CheckReq_descriptor, new String[]{"Map",});
        internal_static_CheckReq_MapEntry_descriptor = internal_static_CheckReq_descriptor.getNestedTypes().get(0);
        internal_static_CheckReq_MapEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_CheckReq_MapEntry_descriptor, new String[]{"Key", "Value",});
        internal_static_Resp_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_Resp_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Resp_descriptor, new String[]{"Code", "Desc",});
    }

    private Service() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    /**
     * Protobuf enum {@code StatusCode}
     */
    public enum StatusCode implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SUCCESS = 1;</code>
         */
        SUCCESS(1),
        /**
         * <code>FAIL = 2;</code>
         */
        FAIL(2),
        ;

        /**
         * <code>SUCCESS = 1;</code>
         */
        public static final int SUCCESS_VALUE = 1;
        /**
         * <code>FAIL = 2;</code>
         */
        public static final int FAIL_VALUE = 2;
        private static final com.google.protobuf.Internal.EnumLiteMap<StatusCode> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
                return StatusCode.forNumber(number);
            }
        };
        private static final StatusCode[] VALUES = values();
        private final int value;

        private StatusCode(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static StatusCode valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static StatusCode forNumber(int value) {
            switch (value) {
                case 1:
                    return SUCCESS;
                case 2:
                    return FAIL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<StatusCode> internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
            return Service.getDescriptor().getEnumTypes().get(0);
        }

        public static StatusCode valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:StatusCode)
    }

    public interface CheckReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:CheckReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        int getMapCount();

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        boolean containsMap(String key);

        /**
         * Use {@link #getMapMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String> getMap();

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        java.util.Map<String, String> getMapMap();

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        /* nullable */
        String getMapOrDefault(String key,
                /* nullable */
                               String defaultValue);

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        String getMapOrThrow(String key);
    }

    public interface RespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Resp)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return Whether the code field is set.
         */
        boolean hasCode();

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return The code.
         */
        StatusCode getCode();

        /**
         * <code>required string desc = 2;</code>
         *
         * @return Whether the desc field is set.
         */
        boolean hasDesc();

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The desc.
         */
        String getDesc();

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The bytes for desc.
         */
        com.google.protobuf.ByteString getDescBytes();
    }

    /**
     * Protobuf type {@code CheckReq}
     */
    public static final class CheckReq extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:CheckReq)
            CheckReqOrBuilder {
        public static final int MAP_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:CheckReq)
        private static final CheckReq DEFAULT_INSTANCE;
        @Deprecated
        public static final com.google.protobuf.Parser<CheckReq> PARSER = new com.google.protobuf.AbstractParser<CheckReq>() {
            @Override
            public CheckReq parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new CheckReq();
        }

        @SuppressWarnings("serial")
        private com.google.protobuf.MapField<String, String> map_;
        private byte memoizedIsInitialized = -1;

        // Use CheckReq.newBuilder() to construct.
        private CheckReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private CheckReq() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return Service.internal_static_CheckReq_descriptor;
        }

        public static CheckReq parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CheckReq parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CheckReq parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CheckReq parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CheckReq parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CheckReq parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CheckReq parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static CheckReq parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static CheckReq parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static CheckReq parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static CheckReq parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static CheckReq parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(CheckReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static CheckReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<CheckReq> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(UnusedPrivateParameter unused) {
            return new CheckReq();
        }

        @SuppressWarnings({"rawtypes"})
        @Override
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 1:
                    return internalGetMap();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return Service.internal_static_CheckReq_fieldAccessorTable.ensureFieldAccessorsInitialized(CheckReq.class, Builder.class);
        }

        private com.google.protobuf.MapField<String, String> internalGetMap() {
            if (map_ == null) {
                return com.google.protobuf.MapField.emptyMapField(MapDefaultEntryHolder.defaultEntry);
            }
            return map_;
        }

        public int getMapCount() {
            return internalGetMap().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @Override
        public boolean containsMap(String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetMap().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMapMap()} instead.
         */
        @Override
        @Deprecated
        public java.util.Map<String, String> getMap() {
            return getMapMap();
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @Override
        public java.util.Map<String, String> getMapMap() {
            return internalGetMap().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @Override
        public /* nullable */
        String getMapOrDefault(String key,
                /* nullable */
                               String defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<String, String> map = internalGetMap().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; map = 1;</code>
         */
        @Override
        public String getMapOrThrow(String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<String, String> map = internalGetMap().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output, internalGetMap(), MapDefaultEntryHolder.defaultEntry, 1);
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<String, String> entry : internalGetMap().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String> map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, map__);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof CheckReq)) {
                return super.equals(obj);
            }
            CheckReq other = (CheckReq) obj;

            if (!internalGetMap().equals(other.internalGetMap())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetMap().getMap().isEmpty()) {
                hash = (37 * hash) + MAP_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMap().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<CheckReq> getParserForType() {
            return PARSER;
        }

        @Override
        public CheckReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class MapDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<String, String> defaultEntry = com.google.protobuf.MapEntry.<String, String>newDefaultInstance(Service.internal_static_CheckReq_MapEntry_descriptor, com.google.protobuf.WireFormat.FieldType.STRING, "", com.google.protobuf.WireFormat.FieldType.STRING, "");
        }

        /**
         * Protobuf type {@code CheckReq}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:CheckReq)
                CheckReqOrBuilder {
            private int bitField0_;
            private com.google.protobuf.MapField<String, String> map_;

            // Construct using Service.CheckReq.newBuilder()
            private Builder() {

            }

            private Builder(BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return Service.internal_static_CheckReq_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(int number) {
                switch (number) {
                    case 1:
                        return internalGetMap();
                    default:
                        throw new RuntimeException("Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableMap();
                    default:
                        throw new RuntimeException("Invalid map field number: " + number);
                }
            }

            @Override
            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return Service.internal_static_CheckReq_fieldAccessorTable.ensureFieldAccessorsInitialized(CheckReq.class, Builder.class);
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                internalGetMutableMap().clear();
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return Service.internal_static_CheckReq_descriptor;
            }

            @Override
            public CheckReq getDefaultInstanceForType() {
                return CheckReq.getDefaultInstance();
            }

            @Override
            public CheckReq build() {
                CheckReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public CheckReq buildPartial() {
                CheckReq result = new CheckReq(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(CheckReq result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.map_ = internalGetMap();
                    result.map_.makeImmutable();
                }
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof CheckReq) {
                    return mergeFrom((CheckReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(CheckReq other) {
                if (other == CheckReq.getDefaultInstance()) return this;
                internalGetMutableMap().mergeFrom(other.internalGetMap());
                bitField0_ |= 0x00000001;
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                com.google.protobuf.MapEntry<String, String> map__ = input.readMessage(MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                                internalGetMutableMap().getMutableMap().put(map__.getKey(), map__.getValue());
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private com.google.protobuf.MapField<String, String> internalGetMap() {
                if (map_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(MapDefaultEntryHolder.defaultEntry);
                }
                return map_;
            }

            private com.google.protobuf.MapField<String, String> internalGetMutableMap() {
                if (map_ == null) {
                    map_ = com.google.protobuf.MapField.newMapField(MapDefaultEntryHolder.defaultEntry);
                }
                if (!map_.isMutable()) {
                    map_ = map_.copy();
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return map_;
            }

            public int getMapCount() {
                return internalGetMap().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @Override
            public boolean containsMap(String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                return internalGetMap().getMap().containsKey(key);
            }

            /**
             * Use {@link #getMapMap()} instead.
             */
            @Override
            @Deprecated
            public java.util.Map<String, String> getMap() {
                return getMapMap();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @Override
            public java.util.Map<String, String> getMapMap() {
                return internalGetMap().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @Override
            public /* nullable */
            String getMapOrDefault(String key,
                    /* nullable */
                                   String defaultValue) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<String, String> map = internalGetMap().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            @Override
            public String getMapOrThrow(String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<String, String> map = internalGetMap().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMap() {
                bitField0_ = (bitField0_ & ~0x00000001);
                internalGetMutableMap().getMutableMap().clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            public Builder removeMap(String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                internalGetMutableMap().getMutableMap().remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String> getMutableMap() {
                bitField0_ |= 0x00000001;
                return internalGetMutableMap().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            public Builder putMap(String key, String value) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                if (value == null) {
                    throw new NullPointerException("map value");
                }
                internalGetMutableMap().getMutableMap().put(key, value);
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; map = 1;</code>
             */
            public Builder putAllMap(java.util.Map<String, String> values) {
                internalGetMutableMap().getMutableMap().putAll(values);
                bitField0_ |= 0x00000001;
                return this;
            }

            @Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:CheckReq)
        }

    }

    /**
     * Protobuf type {@code Resp}
     */
    public static final class Resp extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Resp)
            RespOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int DESC_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Resp)
        private static final Resp DEFAULT_INSTANCE;
        @Deprecated
        public static final com.google.protobuf.Parser<Resp> PARSER = new com.google.protobuf.AbstractParser<Resp>() {
            @Override
            public Resp parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new Resp();
        }

        private int bitField0_;
        private int code_ = 1;
        @SuppressWarnings("serial")
        private volatile Object desc_ = "";
        private byte memoizedIsInitialized = -1;

        // Use Resp.newBuilder() to construct.
        private Resp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Resp() {
            code_ = 1;
            desc_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return Service.internal_static_Resp_descriptor;
        }

        public static Resp parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Resp parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Resp parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Resp parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Resp parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Resp parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Resp parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Resp parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Resp parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static Resp parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Resp parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Resp parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Resp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Resp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Resp> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(UnusedPrivateParameter unused) {
            return new Resp();
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return Service.internal_static_Resp_fieldAccessorTable.ensureFieldAccessorsInitialized(Resp.class, Builder.class);
        }

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return Whether the code field is set.
         */
        @Override
        public boolean hasCode() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required .StatusCode code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public StatusCode getCode() {
            StatusCode result = StatusCode.forNumber(code_);
            return result == null ? StatusCode.SUCCESS : result;
        }

        /**
         * <code>required string desc = 2;</code>
         *
         * @return Whether the desc field is set.
         */
        @Override
        public boolean hasDesc() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The desc.
         */
        @Override
        public String getDesc() {
            Object ref = desc_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    desc_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string desc = 2;</code>
         *
         * @return The bytes for desc.
         */
        @Override
        public com.google.protobuf.ByteString getDescBytes() {
            Object ref = desc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDesc()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeEnum(1, code_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, code_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Resp)) {
                return super.equals(obj);
            }
            Resp other = (Resp) obj;

            if (hasCode() != other.hasCode()) return false;
            if (hasCode()) {
                if (code_ != other.code_) return false;
            }
            if (hasDesc() != other.hasDesc()) return false;
            if (hasDesc()) {
                if (!getDesc().equals(other.getDesc())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasCode()) {
                hash = (37 * hash) + CODE_FIELD_NUMBER;
                hash = (53 * hash) + code_;
            }
            if (hasDesc()) {
                hash = (37 * hash) + DESC_FIELD_NUMBER;
                hash = (53 * hash) + getDesc().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Resp> getParserForType() {
            return PARSER;
        }

        @Override
        public Resp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Resp}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Resp)
                RespOrBuilder {
            private int bitField0_;
            private int code_ = 1;
            private Object desc_ = "";

            // Construct using Service.Resp.newBuilder()
            private Builder() {

            }

            private Builder(BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return Service.internal_static_Resp_descriptor;
            }

            @Override
            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return Service.internal_static_Resp_fieldAccessorTable.ensureFieldAccessorsInitialized(Resp.class, Builder.class);
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = 1;
                desc_ = "";
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return Service.internal_static_Resp_descriptor;
            }

            @Override
            public Resp getDefaultInstanceForType() {
                return Resp.getDefaultInstance();
            }

            @Override
            public Resp build() {
                Resp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Resp buildPartial() {
                Resp result = new Resp(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(Resp result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.desc_ = desc_;
                    to_bitField0_ |= 0x00000002;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Resp) {
                    return mergeFrom((Resp) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Resp other) {
                if (other == Resp.getDefaultInstance()) return this;
                if (other.hasCode()) {
                    setCode(other.getCode());
                }
                if (other.hasDesc()) {
                    desc_ = other.desc_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasCode()) {
                    return false;
                }
                if (!hasDesc()) {
                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                int tmpRaw = input.readEnum();
                                StatusCode tmpValue = StatusCode.forNumber(tmpRaw);
                                if (tmpValue == null) {
                                    mergeUnknownVarintField(1, tmpRaw);
                                } else {
                                    code_ = tmpRaw;
                                    bitField0_ |= 0x00000001;
                                }
                                break;
                            } // case 8
                            case 18: {
                                desc_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @return Whether the code field is set.
             */
            @Override
            public boolean hasCode() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @return The code.
             */
            @Override
            public StatusCode getCode() {
                StatusCode result = StatusCode.forNumber(code_);
                return result == null ? StatusCode.SUCCESS : result;
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(StatusCode value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                code_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required .StatusCode code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 1;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return Whether the desc field is set.
             */
            public boolean hasDesc() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return The desc.
             */
            public String getDesc() {
                Object ref = desc_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        desc_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @param value The desc to set.
             * @return This builder for chaining.
             */
            public Builder setDesc(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                desc_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return The bytes for desc.
             */
            public com.google.protobuf.ByteString getDescBytes() {
                Object ref = desc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    desc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @param value The bytes for desc to set.
             * @return This builder for chaining.
             */
            public Builder setDescBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                desc_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>required string desc = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDesc() {
                desc_ = getDefaultInstance().getDesc();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Resp)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
